name: Java CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone JOSM
      run: svn co --depth=immediates https://josm.openstreetmap.de/osmsvn/applications/editors/josm josm && cd josm && svn up --set-depth=immediates plugins && svn up --set-depth=infinity --accept=theirs-full core i18n plugins/{00_core_test_config,00_core_test_lib,00_core_tools,00_tools}
    - uses: actions/checkout@v3
      with:
        path: josm/plugins/
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        path: |
          ~/.ivy2/cache/
          ~/work/josm/josm/tools/
        key: ${{ runner.os }}-ivy2-${{ hashFiles('build.xml', 'ivy.xml', '../00_core_tools/ivy.xml') }}
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
